[entryPoints]
  [entryPoints.websecure]
    address = ":6443"
    [entryPoints.websecure.http.tls]
      [[entryPoints.websecure.http.tls.domains]]
        main = "10.0.0.30"
  [entryPoints.web]
    address = ":80"


[providers.file]
  directory = "/etc/traefik/conf/"
  
[serversTransport]
  insecureSkipVerify = true

[api]
  dashboard = true
  insecure = true
